apiVersion: v1
appVersion: 1.11.2
description: Chart for Apache Flink
name: flink
version: 0.2.0
maintainers:
  - name: charts-maintainers
    email: charts-maintainers@riskfocus.com
home: https://github.com/riskfocus/helm-charts-public
